name: Build LibreELEC-RR 9.x for AMLGX

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  REPO_URL: https://github.com/maskedeken/LibreELEC-RR
  BRANCH: master-rr
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt-get -qq update
        sudo timedatectl set-timezone "$TZ"

    - name: Clone source code
      run: |
        git clone --recurse-submodules -b $BRANCH $REPO_URL libreelec

    - name: Build toolchain
      id: toolchain
      run: |
        cd libreelec
        PROJECT=Amlogic DEVICE=AMLGX ARCH=arm ./scripts/build_mt toolchain

    - name: Build MAME 2003 Plus
      id: mame2003plus
      run: |
        cd libreelec
        PROJECT=Amlogic DEVICE=AMLGX ARCH=arm ./scripts/build_mt libretro-mame2003_plus

    - name: Build MAME 2010
      id: mame2010
      run: |
        cd libreelec
        PROJECT=Amlogic DEVICE=AMLGX ARCH=arm ./scripts/install zlib
        PROJECT=Amlogic DEVICE=AMLGX ARCH=arm ./scripts/build_mt libretro-mame2010

    - name: Build FireBurn Neo
      id: fbneo
      run: |
        cd libreelec
        PROJECT=Amlogic DEVICE=AMLGX ARCH=arm ./scripts/build_mt fbneo

    - name: Build PPSSPP-SDL
      id: ppsspp
      run: |
        cd libreelec
        PROJECT=Amlogic DEVICE=AMLGX ARCH=arm ./scripts/build_mt ppsspp

    - name: Build Openbor
      id: openbor
      run: |
        cd libreelec
        PROJECT=Amlogic DEVICE=AMLGX ARCH=arm ./scripts/build_mt openbor

    - name: Make image
      id: image
      run: |
        cd libreelec
        PROJECT=Amlogic DEVICE=AMLGX ARCH=arm make image -j8

    - name: Generate release tag
      id: tag
      run: |
        echo "::set-output name=release_tag::$(date +"%Y.%m.%d-%H%M")"
        echo "::set-output name=status::success"

    - name: Upload firmware to release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.tag.outputs.release_tag }}
        files: libreelec/target/*.gz

    - name: Delete workflow runs
      uses: GitRML/delete-workflow-runs@main
      with:
        retain_days: 1
        keep_minimum_runs: 3

